-- Seed data: orange_users, orange_roles, orange_permissions, orange_role_permission, orange_user_role
--
-- GENERATED by bin/dbExport from the phinx migrations in the
-- Orange-Application repo - do not edit here. Change a migration and run
-- "composer db:export".
--
-- Loaded automatically on the first "docker compose up" of the mysql
-- sandbox; the numeric prefixes are the load order.

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `orange_users` WRITE;
/*!40000 ALTER TABLE `orange_users` DISABLE KEYS */;
INSERT INTO `orange_users` (`id`, `username`, `email`, `password`, `is_active`, `is_deleted`) VALUES (1,'admin','admin@example.com','$2y$12$yvswuQcBPiKE636I66YLcuwEo5y3.DtWvoy0NrJXopJuAX0Jd/iwS',1,0),(2,'guest','guest@example.com','',0,0);
/*!40000 ALTER TABLE `orange_users` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `orange_roles` WRITE;
/*!40000 ALTER TABLE `orange_roles` DISABLE KEYS */;
INSERT INTO `orange_roles` (`id`, `name`, `description`, `migration`, `is_active`) VALUES (1,'orders manager','May create, edit and delete orders',NULL,1);
/*!40000 ALTER TABLE `orange_roles` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `orange_permissions` WRITE;
/*!40000 ALTER TABLE `orange_permissions` DISABLE KEYS */;
INSERT INTO `orange_permissions` (`id`, `key`, `description`, `group`, `migration`, `is_active`) VALUES (1,'orders.create','Create an order','orders',NULL,1),(2,'orders.delete','Delete an order','orders',NULL,1),(3,'orders.update','Edit an order','orders',NULL,1);
/*!40000 ALTER TABLE `orange_permissions` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `orange_role_permission` WRITE;
/*!40000 ALTER TABLE `orange_role_permission` DISABLE KEYS */;
INSERT INTO `orange_role_permission` (`role_id`, `permission_id`) VALUES (1,1),(1,2),(1,3);
/*!40000 ALTER TABLE `orange_role_permission` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `orange_user_role` WRITE;
/*!40000 ALTER TABLE `orange_user_role` DISABLE KEYS */;
INSERT INTO `orange_user_role` (`user_id`, `role_id`) VALUES (1,1);
/*!40000 ALTER TABLE `orange_user_role` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
